apiVersion: apps/v1
kind: Namespace
metadata:
  name: my
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: my
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
       app: myapp
    spec:
      containers:
        - name: student-managment
          image: shubhamt1/myapp:latest
          ports:
            - containerPort: 7788
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7788
      nodePort: 30007
